id: P004304
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:09:08.150465
source_metadata:
  id: bdr:W30017
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་གཞག།（མཚོ་སྔོན་མི་རིགས་དཔེ་སྐྲུན་ཁང་།）
  author: ''
  volumes:
    c37a08d46376412f9653f0d292931178:
      image_group_id: I5756
      title: ''
      volume_number: 1
      total_pages: 1138
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
